services:
  backend:
    image: test-backend:1.0
    container_name: test-backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:14.12
    restart: always
    container_name: test-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testBackend 
    ports:
      - '5434:5432'
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data
      - ./scheme.sql:/docker-entrypoint-initdb.d/scheme.sql

networks:
  backend:
    name: backend 
    driver: bridge

volumes:
  db:
