services:
  db:
    image: postgres:14.12
    restart: always
    container_name: test-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timetable
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
